USE AdventureWorks2012
/*
SUM = SOMA
MAX = VALOR MAIS ALTO
MIN = VALOR MINIMO
AVG = MEDIA
*/
-- QUANTOS PRODUTOS VERMELHOS TEM PRECO ENTRE 500 E 100 USD
SELECT COUNT(*) AS 'PRODUTOS VERMELHOS' FROM Production.Product
WHERE Color = 'RED'
AND ListPrice BETWEEN '500' AND '1000'

-- PRODUTOS QUE TEM ESSA SEQ DE CARACTER NO NOME ROAD
SELECT * FROM Production.Product
WHERE NAME LIKE '%ROAD%'

SELECT COUNT(NAME) FROM Production.Product
WHERE NAME LIKE '%ROAD%'

--

SELECT TOP 10 * FROM Sales.SalesOrderDetail ORDER BY LineTotal DESC

SELECT TOP 10 SUM(LineTotal) AS TOTALVENDAS FROM Sales.SalesOrderDetail

SELECT MAX(LineTotal) AS TOTALVENDAS FROM Sales.SalesOrderDetail

SELECT MIN(LineTotal) AS TOTALVENDAS FROM Sales.SalesOrderDetail

SELECT AVG(LineTotal) AS TOTALVENDAS FROM Sales.SalesOrderDetail

SELECT FirstName, COUNT(FirstName) AS QTDE FROM Person.Person
GROUP BY FirstName

SELECT SpecialOfferID, SUM(UnitPrice) AS 'TOTAL VENDAS' FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID
ORDER BY SpecialOfferID ASC

SELECT SpecialOfferID, SUM(UnitPrice) AS 'TOTAL VENDAS' FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID
ORDER BY SUM(UnitPrice) DESC


-- QUANTOS PRODUTOS FORAM VENDIDOS ATÉ HOJE

SELECT ProductID, COUNT(ProductID) AS 'QUANTIDADES DE PRODUTOS' FROM Sales.SalesOrderDetail
GROUP BY ProductID

-- PRODUCTION.PRODUCT - PRODUTOS PRATA - SILVER/ MEDIA PREÇO - LISTPRICE

SELECT Color, AVG(ListPrice) AS 'MEDIA DE PREÇO' FROM Production.Product
WHERE Color = 'SILVER'
GROUP BY Color

-- QUANTAS PESSOAS TEM MESMO NOME DO MEIO 

SELECT MiddleName, COUNT(MiddleName) AS QTDE FROM Person.Person
GROUP BY MiddleName
ORDER BY MiddleName

-- TODOS VÃO GROUP BY
-- 1 QUAL A MEDIA QUE CADA PRODUTO É VENDIDO
SELECT ProductID, AVG(OrderQty) AS QTDE FROM Sales.SalesOrderDetail
GROUP BY ProductID


-- 2 QUAIS OS 10 PRODUTOS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA AGRUPADOS
--POR PRODUTO DO MAIOR PARA O MENOR (SALESORDERDETAIL)
SELECT TOP 10 ProductID, SUM(LineTotal) AS QTDE FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) DESC

-- 3 QUANTOS PRODUTOS E QUAL A QTDE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS ORDENS DE
-- SERVIÇO (WORKORDER) - AGRUPAR PELO ID DO PRODUTO (PRODUCTION.WORKORDER)

SELECT ProductID, COUNT(ProductID) AS QTDE, AVG(OrderQty) AS MEDIA  
FROM Production.WorkOrder
GROUP BY ProductID


SELECT FirstName, COUNT(FirstName) AS QTDE 
FROM Person.Person
WHERE FirstName LIKE 'A%'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10

-- AGRUPAR OS PRODUTOS(PRODUCTID) POR VENDAS TOTAIS(LINETOTAL) ENTRE 162K E 500K

SELECT ProductID, SUM(LineTotal) AS 'TOTAIS DE VENDAS' 
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000

-- QUAIS PRODUTOS NÃO ESTÃO TRAZENDO EM MEDIA VENDAS DE UM MILHÃO NO TOTAL
SELECT ProductID, AVG(LineTotal) AS TOTAL FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) < 1000